services:
  # --- Backend (FastAPI) ---
  - type: web
    name: dojorise-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dojorise-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    region: frankfurt

  # --- Frontend (Next.js) ---
  - type: web
    name: dojorise-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://dojorise-api.onrender.com
    plan: free
    region: frankfurt

databases:
  - name: dojorise-db
    plan: free
    region: frankfurt
